name: Publish

on:
  release:
    types:
    - created

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 11
    - uses: android-actions/setup-android@v2
    - id: tag
      name: Extract tag name
      uses: actions/github-script@v2
      with:
        script: |
          const tagNS = "refs/tags/";
          const ref = context.ref;
          return ref && ref.startsWith(tagNS)
            ? ref.substr(tagNS.length + (ref[tagNS.length] == "v"))
            : '';
        result-encoding: string
    - uses: gradle/gradle-build-action@v2
      with:
        arguments: -Pversion=${{ steps.tag.outputs.result }} publishAllPublicationsToGitHubPackagesRepository
      env:
        ORG_GRADLE_PROJECT_GitHubPackagesUsername: ${{ github.actor }}
        ORG_GRADLE_PROJECT_GitHubPackagesPassword: ${{ secrets.GITHUB_TOKEN }}
